spring:
  security:
    oauth2:
      client:
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/7918fc3e-3435-4d67-9176-761977074afa/v2.0
            user-name-attribute: name
        registration:
          azure-dev:
            provider: azure
            client-id: ddee8633-dcef-418f-98f3-9c7ae5cc41eb
            client-secret: C6q8Q~y2NzRYNe1.FzOd8fay2d6jE_gtEhoL1b-9
            scope:
              - openid
              - email
              - profile


# Group mapping
baeldung:
  jwt:
    authorization:
      group-to-authorities:
        "f07c6283-37a0-4d9b-9fbe-89e9918ed464": GROUP1
        "4b593ac6-7156-48c9-9a6e-b2e7b53f1792": DEVELOPER
